# Generated by Django 3.2.9 on 2021-12-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_core'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Core',
        ),
    ]
